### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by bradfrost** [EvanLovely/grunt-pattern-lab-component-builder#1]
I don't really have specific issues, other than just generally wanting to know how to make this work.

I'm specifically curious about what `template: 'templates/colors.mustache'` is. Does that live in `_patterns/templates`? Right now, I have my colors swatches living `_patterns/atoms/global/colors.mustache`. Would I update the template path to that?

I'm also curious about this: `dest: tmp/colors.mustache' What does that do exactly? 

Thanks for putting this together. I'm really looking forward to wrapping my head around it!

**Comment by EvanLovely** [comment]
@bradfrost I'm in the middle of refactor and clean up that will include some documentation and I'm slatted to be tackling it this Thursday. I'll ping you when there's some more concrete direction. The directions are pretty crap right now, sorry. Here's basically what it does below, but just give me a week.

I should highlight that what this mainly does is build JSON from Scss files. So my `colors.mustache` file looks like this:

``` handlebars
<ul class="sg-colors">
  {{#pl_colors}}
    <li>
      <div class="sg-swatch" style="background: {{value}};"></div>
      <div class="sg-info">
        <h6>{{value}}</h6>
        Sass Variable: <br>
        {{name}}
      </div>
    </li>
  {{/pl_colors}}
</ul>
```

and this is what gets generated by this plugin:

``` json
{
  "pl_colors": [
    {
      "name": "$color--gray--lightest",
      "value": "hsl(0, 0%, 85.9%)"
    },
    {
      "name": "$color--gray--lighter",
      "value": "hsl(0, 0%, 78%)"
    },
    {
      "name": "$color--gray--light",
      "value": "hsl(0, 0%, 60%)"
    },
    {
      "name": "$color--gray",
      "value": "hsl(228, 2.3%, 41.8%)"
    },
    {
      "name": "$color--gray--dark",
      "value": "hsl(0, 0%, 30%)"
    },
    {
      "name": "$color--gray--darker",
      "value": "hsl(0, 0%, 20%)"
    },
    {
      "name": "$color--gray--darkest",
      "value": "hsl(0, 0%, 16%)"
    }
  ]
}
```

This is the source that the plugin gets pointed at:

``` scss
$color--gray--lightest: hsl(0, 0%, 85.9%);
$color--gray--lighter: hsl(0, 0%, 78%);
$color--gray--light: hsl(0, 0%, 60%);
$color--gray: hsl(228, 2.3%, 41.8%);
$color--gray--dark: hsl(0, 0%, 30%);
$color--gray--darker: hsl(0, 0%, 20%);
$color--gray--darkest: hsl(0, 0%, 16%);
```

**Comment by EvanLovely** [comment]
Just looked at the readme and realized how off it was; sorry! 😜 So your Gruntfile should look like this:

``` js
pattern_lab_component_builder: {
    colors: {
      options: {
        regex: "^\\$color--.*",
        allow_var_values: false
      },
      src: 'scss/global/variables/_colors.scss',
      dest: 'source/_patterns/00-atoms/01-global/00-colors.json'
    },
    fonts: {
      options: {
        'regex': "^\\$type.*"
      },
      src: "scss/global/variables/_type-sizes.scss",
      dest: "source/_patterns/00-atoms/02-text/02-type-sizes.json"
    },
  }
```
